sudo: required
services:
  - docker

before_install:
  - docker build -t kmanek/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true kmanek/react-test npm test -- --coverage

after_success:
  - docker build -t kmanek/multi-client ./client
  - docker build -t kmanek/multi-nginx ./nginx
  - docker build -t kmanek/multi-server ./server
  - docker build -t kmanek/multi-worker ./worker
  - echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
  - docker push kmanek/multi-client
  - docker push kmanek/multi-nginx
  - docker push kmanek/multi-server
  - docker push kmanek/multi-worker
